name: Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{vars.GO_VERSION}}
          cache: false

      - name: Install dependencies
        run: |
          go mod tidy

      - name: Test
        run: |
          go test -v ./...